export const agents = [
  {
    id: 'agent_1',
    name: 'WhatsApp Lead Booster',
    builder_name: 'Arjun Patel',
    tagline: 'Turn WhatsApp chats into qualified sales leads',
    description: 'Automates qualification questions, captures requirements, and schedules demos via WhatsApp.',
    category: 'Lead Generation',
    price_monthly: 4999,
    status: 'published',
    rating: 4.9,
    purchases: 1204,
    integrations: ['WhatsApp', 'Google Sheets', 'CRM'],
    use_cases: ['Lead capture', 'Qualification', 'Booking demos'],
    features: ['Smart forms', 'Auto follow-up', 'CRM sync'],
    languages_supported: ['Hindi', 'English'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_2',
    name: 'Voice Support Triage',
    builder_name: 'Neha Sharma',
    tagline: 'AI voice agent for instant ticket triage',
    description: 'Handles common queries by voice, routes complex issues, and escalates tickets with context.',
    category: 'Customer Support',
    price_monthly: 3999,
    status: 'published',
    rating: 4.8,
    purchases: 876,
    integrations: ['WhatsApp', 'Email', 'Zendesk'],
    use_cases: ['Support triage', 'FAQ resolution', 'Escalation'],
    features: ['Voice transcription', 'Intent detection', 'Ticket routing'],
    languages_supported: ['Hindi', 'English'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_3',
    name: 'Appointment Booking Assistant',
    builder_name: 'Sahil Khan',
    tagline: 'Auto-book appointments 24/7',
    description: 'Collects service details, checks availability, and confirms bookings for local businesses.',
    category: 'Booking',
    price_monthly: 3499,
    status: 'published',
    rating: 4.7,
    purchases: 642,
    integrations: ['WhatsApp', 'Calendar', 'SMS'],
    use_cases: ['Salons', 'Clinics', 'Consulting'],
    features: ['Availability checks', 'Reminders', 'No-show reduction'],
    languages_supported: ['Hindi', 'English'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_4',
    name: 'Realtime Product Quiz',
    builder_name: 'Riya Iyer',
    tagline: 'Help customers choose the right product',
    description: 'Asks a few questions, recommends products, and sends a checkout link via WhatsApp.',
    category: 'E-commerce',
    price_monthly: 5999,
    status: 'published',
    rating: 4.9,
    purchases: 1033,
    integrations: ['WhatsApp', 'Shopify', 'Payments'],
    use_cases: ['Product recommendation', 'Lead nurturing', 'Sales conversion'],
    features: ['Recommendation logic', 'FAQ handling', 'Order handoff'],
    languages_supported: ['English', 'Tamil', 'Hindi'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_5',
    name: 'Automation for Internal Ops',
    builder_name: 'Vikram Rao',
    tagline: 'Move requests to action automatically',
    description: 'Turns employee WhatsApp/Email requests into structured workflows with approvals.',
    category: 'Automation',
    price_monthly: 7499,
    status: 'published',
    rating: 4.8,
    purchases: 511,
    integrations: ['WhatsApp', 'Slack', 'Google Drive'],
    use_cases: ['Approvals', 'Task routing', 'Document capture'],
    features: ['Workflow engine', 'Templates', 'Audit trail'],
    languages_supported: ['English', 'Hindi'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_6',
    name: 'Website-to-WhatsApp Concierge',
    builder_name: 'Kavya Menon',
    tagline: 'Turn website visitors into WhatsApp conversations',
    description: 'Captures intent from forms, replies instantly, and sends tailored next steps.',
    category: 'Website',
    price_monthly: 4999,
    status: 'published',
    rating: 4.9,
    purchases: 899,
    integrations: ['WhatsApp', 'Website', 'CRM'],
    use_cases: ['Visitor engagement', 'Lead capture', 'Follow-ups'],
    features: ['Form intent', 'Instant replies', 'Follow-up sequences'],
    languages_supported: ['English', 'Hindi'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_7',
    name: 'Booking & Payments Collector',
    builder_name: 'Arif Ansari',
    tagline: 'Collect payments and confirm bookings',
    description: 'Guides users to checkout, confirms payment, and triggers delivery timelines.',
    category: 'Payments',
    price_monthly: 8999,
    status: 'published',
    rating: 4.8,
    purchases: 412,
    integrations: ['WhatsApp', 'Razorpay', 'Supabase'],
    use_cases: ['Escrow workflow', 'Order confirmation', 'Delivery scheduling'],
    features: ['Webhook handling', 'Status updates', 'Receipt capture'],
    languages_supported: ['Hindi', 'English'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
  {
    id: 'agent_8',
    name: 'Custom Business Agent Builder',
    builder_name: 'Meera Kulkarni',
    tagline: 'Design a tailored automation for your workflow',
    description: 'A flexible agent that adapts to your business rules, FAQs, and escalation paths.',
    category: 'Custom',
    price_monthly: 9999,
    status: 'published',
    rating: 5.0,
    purchases: 238,
    integrations: ['WhatsApp', 'Webhook', 'Database'],
    use_cases: ['Unique workflows', 'Complex routing', 'Internal approvals'],
    features: ['Custom prompt', 'Rules engine', 'Escalation'],
    languages_supported: ['English', 'Marathi', 'Hindi'],
    demo_video_url: null,
    demo_video_thumbnail: null,
  },
];

export const builders = [
  { id: 'builder_1', full_name: 'Aman Verma', avatar_url: null, city: 'Delhi' },
  { id: 'builder_2', full_name: 'Priya Nair', avatar_url: null, city: 'Bengaluru' },
  { id: 'builder_3', full_name: 'Rahul Singh', avatar_url: null, city: 'Mumbai' },
  { id: 'builder_4', full_name: 'Ananya Das', avatar_url: null, city: 'Kolkata' },
  { id: 'builder_5', full_name: 'Vishal Reddy', avatar_url: null, city: 'Hyderabad' },
  { id: 'builder_6', full_name: 'Simran Kaur', avatar_url: null, city: 'Chandigarh' },
];

export const tickerNews = [
  'India sees rapid adoption of AI chatbots for customer support across SMBs.',
  'Rising demand for WhatsApp-first AI agents as customers prefer conversational commerce.',
  'Supabase-based stacks are gaining traction for building AI apps with realtime data.',
  'Businesses are shifting from generic chat to workflow automation: intake → approve → execute.',
  'Whisper and speech models are enabling voice-based support at scale in Indian languages.',
  'Razorpay integrations are helping automate payments and escrow flows for service marketplaces.',
  'AI orchestration frameworks are improving reliability of multi-step agent flows.',
  'More builders are packaging “vertical agents” for specific industries like clinics and e-commerce.',
  'Compliance and security practices are becoming a key selling point for AI deployments.',
  'Marketplaces are turning AI agents into subscription products with clearer ROI reporting.',
];

export const businessPlans = [
  { id: 'plan_free', name: 'Free', price_monthly: 0, description: 'Try the marketplace with limited usage.' },
  { id: 'plan_starter', name: 'Starter', price_monthly: 999, description: 'For early-stage builders and pilots.' },
  { id: 'plan_growth', name: 'Growth', price_monthly: 2499, description: 'Popular: more agents, more automation volume.' },
  { id: 'plan_pro', name: 'Pro', price_monthly: 4999, description: 'Advanced workflows and higher usage limits.' },
];

export const builderPlans = [
  { id: 'bp_free', name: 'Free', price_monthly: 0, description: 'Publish simple prototypes.' },
  { id: 'bp_starter', name: 'Starter', price_monthly: 2000, description: 'Build and deploy with more capacity.' },
  { id: 'bp_growth', name: 'Growth', price_monthly: 5000, description: 'Popular: higher deployment and studio limits.' },
  { id: 'bp_business', name: 'Business', price_monthly: 15000, description: 'For teams building multiple production agents.' },
];

